/// Flutter icons ServiceIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ServiceIcon
///      fonts:
///       - asset: fonts/ServiceIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ServiceIcon {
  ServiceIcon._();

  static const _kFontFam = 'ServiceIcon';
  static const String _kFontPkg = null;

  static const IconData suitcase = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
